[package]
name = "wiretui-adapters"
edition = "2024"
description = "Implement outbound ports, implement inbound adapters to access the application"
publish = false
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "adapters"

[dependencies]
application = { workspace = true }
domain = { workspace = true }
ports = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
zbus = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
ratatui-textarea = { workspace = true }
