[package]
name = "wiretui-bin"
edition = "2024"
description = "A minimal keyboard-driven TUI to manage WireGuard VPN connections"
publish = false
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
adapters = { path = "../../src-libs/adapters" }
application = { path = "../../src-libs/application" }
