[package]
name = "wiretui-bin"
edition = "2024"
description = "A minimal keyboard-driven TUI to manage WireGuard VPN connections"
publish = false
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "wiretui"
path = "src/main.rs"

[dependencies]
adapters = { path = "../adapters", package = "wiretui-adapters" }
application = { path = "../application", package = "wiretui-application" }
env_logger = { workspace = true }
log = { workspace = true }
