[package]
name = "wiretui-bin"
edition = "2024"
description = "A minimal keyboard-driven TUI to manage WireGuard VPN connections"
publish = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "wiretui"
path = "src/main.rs"

[dependencies]
adapters.workspace = true
application.workspace = true
env_logger.workspace = true
log.workspace = true
